### ISSUE TITLE
Failed to load the local-history package

### ISSUE THREAD

**Issue by vihryn** [Nicolab/atom-local-history#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.3
**Thrown From**: [local-history](https://github.com/Nicolab/atom-local-history) package, v3.2.2

### Stack Trace

Failed to load the local-history package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/vihryn/.atom/packages/local-history/lib/utils.js:8:24)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".gitkeep"
    ],
    "disabledPackages": [
      "git-merge-conflicts",
      "language-objective-c",
      "linter-handlebars"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "local-history": {}
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.5.0
atom-jshint, v2.0.0
better-handlebars, v0.1.1
ember-snippets, v1.2.1
javascript-snippets, v1.0.0
language-handlebars, v0.2.0
language-vhdl, v0.7.1
local-history, v3.2.2
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by Nicolab** [comment]
Hello,

can you uninstall and reinstall local-history ?

**Comment by Nicolab** [comment]
Work fine with V3.2.3
